### ISSUE TITLE
[Idea] Add Link header of pushed ressources

### ISSUE THREAD

**Issue by Neirda24** [dunglas/vulcain#48]
As suggested in the title, an idea would be for vulcain to add the Link header for every pushed ressources. It allows Vulcain to be behind a reverse proxy that will handle the pushed itself if necessary.

At least it would be great to have it if Server Push is not available (eg: Vulcain in http mode)

**Comment by dunglas** [comment]
It's already implemented in the gateway server! However, be careful to one thing: most reverse proxies don't forward headers when requesting resources to push. It means that it will work well for public resources, but not for resources requiring authentication (because the most reverse proxies will not forward `Authorization` and `Cookie` headers). With some proxies, you can whitelist the headers to forward.
