### ISSUE TITLE
Chrome intends to remove support of Server Push technology

### ISSUE THREAD

**Issue by qWici** [dunglas/vulcain#70]
[Conversation](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1)

**Comment by dunglas** [comment]
I published a Twitter thread explaining what it changes for Vulcain: https://twitter.com/dunglas/status/1326552735404060672

TL;DR Vulcain will fallback on `Preload` links (which are already supported) and Early Hints when they will be adopted by browsers. `Preload` links introduce a bit more latency than Server Push (1 RTT actually), but also fix some issues. Anyway, even with `Preload` links instead of Server Push, the global approach is still faster and cleaner than using compound documents.

**Comment by qWici** [comment]
Got it, thanks

**Comment by sbward** [comment]
How will the updated approach be faster than a compound document if there is a minimum of 2 RTT to implement the protocol?

**Comment by dunglas** [comment]
@sbward because HTTP cache. The cache dynamic is better with many small documents instead of a big compound one. And actually the cache dynamic will be better with 103 than with server push because browsers never properly supported HTTP cache for pushed resources(even if theoretically possible).
